# Copyright 2026 Leonan Carvalho
# SPDX-License-Identifier: agpl

version: "2"
linters:
  default: none
  enable:
    - govet
    - staticcheck
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
run:
  modules-download-mode: readonly
  tests: true
  timeout: 5m
