[settings]
experimental = true

[env]
_.file = ".env.local"

[tools]
go = "1.26.1"
golangci-lint = "v2.11.4"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"go:github.com/daixiang0/gci" = "latest"

[tasks.local]
run = "go run ."

[tasks.build]
run = "go build -o docscout-mcp ."

[tasks.test]
run = "go test ./..."

[tasks.format]
run = "gci write -s standard -s default -s localmodule --skip-generated --skip-vendor ."
run_windows = "cmd /c gci write -s standard -s default -s localmodule --skip-generated --skip-vendor ."